### PR TITLE
Fix AttributeError: 'DataFrame' object has no attribute 'append'

### PR DESCRIPTION
**Pull request by fancyfsz**

### CODE REVIEW

**Comment by fancyfsz** [comment]
I checked my pandas version was 2.0.2. But requirements.txt given is 1.2.5. So no issues here.

**Comment by fancyfsz** [comment]
Reference:
https://pandas.pydata.org/pandas-docs/version/1.2/reference/api/pandas.concat.html
https://stackoverflow.com/questions/75956209/dataframe-object-has-no-attribute-append
So I think here concat is more suitable.

**Comment by fancyfsz** [comment]
Don't know why if I install pandas 1.2.5. When I run, it will tip ImportError: Plotly express requires pandas to be installed. Then I change it to pandas 2.0.2 this error gone.

**Comment by fancyfsz** [comment]
My fix has bug, just ignore.

**Comment by castroavila** [comment]
Were you able to run the code ?

**Comment by fancyfsz** [comment]
> Were you able to run the code ?

I fixed it by changing pandas version to 2.0.2 and modified some code. So I was able to run my code. Later I met some issues with pygraphviz, I fixed it both on Mac and Windows.

**Pull request closed without merging**
